import { input } from "./input.js";
import { audio } from "./audio.js";
import { storage } from "./storage.js";
import { shake, updateShake, particleBurst, updateParticles, fitCanvas, reducedMotion, rounded } from "./fx.js";
const diff={easy:{delay:.38,speed:250,error:72},normal:{delay:.18,speed:390,error:34},unfair:{delay:.055,speed:590,error:11}};
export class Pong {
  constructor(canvas,ui){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.ui=ui;this.mode="cpu";this.level="normal";this.best=storage.get("pong-best-rally",0);this.streak=storage.get("pong-streak",0);this.running=false;this.last=0;this.drag={};input.bindDrag(canvas,(x,y)=>this.drag={x,y});}
  start(mode="cpu",level="normal"){this.mode=mode;this.level=level;this.resetMatch();this.running=true;this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
  resetMatch(){this.score=[0,0];this.rally=0;this.serveTo=1;this.particles=[];this.paused=false;this.shake=shake(0);this.slow=0;this.resetRound();}
  resetRound(){this.paddles=[{y:.5,flash:0},{y:.5,flash:0}];this.ball={x:.5,y:.5,vx:0,vy:0,r:11,squash:0};this.count=3.1;this.cpuClock=0;this.cpuTarget=.5;this.rally=0;}
  world(){const {w,h}=fitCanvas(this.canvas);const W=Math.min(w,h*16/9),H=W*9/16;return{w,h,W,H,x:(w-W)/2,y:(h-H)/2};}
  serve(){const direction=this.serveTo===0?-1:1;this.ball.vx=direction*430;this.ball.vy=(Math.random()-.5)*220;audio.count();}
  player(dt){let a=0,b=0;if(this.mode==="2p"){a=(input.down("w")?-1:0)+(input.down("s")?1:0);b=(input.down("arrowup")?-1:0)+(input.down("arrowdown")?1:0);}else a=(input.down("w","arrowup")?-1:0)+(input.down("s","arrowdown")?1:0);const p=this.paddles[0];p.y+=a*1.25*dt;if(this.drag.y){const rect=this.canvas.getBoundingClientRect(), onRight=this.drag.x>rect.left+rect.width/2;if(this.mode==="2p"?(onRight?this.paddles[1]:p):!onRight){(this.mode==="2p"&&onRight?this.paddles[1]:p).y=(this.drag.y-rect.top)/rect.height;}}if(this.mode==="2p")this.paddles[1].y+=b*1.25*dt;this.paddles.forEach(p=>p.y=Math.max(.11,Math.min(.89,p.y)));}
  cpu(dt){if(this.mode==="2p")return;const d=diff[this.level];this.cpuClock-=dt;if(this.cpuClock<=0){this.cpuClock=d.delay;let target=this.ball.y;if(this.ball.vx>0){const time=(.93-this.ball.x)/Math.max(1,this.ball.vx);target+=this.ball.vy*time;}this.cpuTarget=Math.max(.11,Math.min(.89,target+(Math.random()-.5)*d.error/500));}const p=this.paddles[1],delta=this.cpuTarget-p.y;p.y+=Math.sign(delta)*Math.min(Math.abs(delta),d.speed/500*dt);p.y=Math.max(.11,Math.min(.89,p.y));}
  scorePoint(side){this.score[side]++;audio.score();particleBurst(this.particles,.5,.5,side===0?"#c7ff3c":"#ff4d9b",26,1.3);this.serveTo=side===0?1:0;this.shake=shake(9,.18);const done=Math.max(...this.score)>=7&&Math.abs(this.score[0]-this.score[1])>=2;if(done){this.running=false;if(this.mode==="cpu"){this.streak=side===0?this.streak+1:0;storage.set("pong-streak",this.streak);}this.ui.show(side===0?"MATCH WON":"MATCH LOST",`${this.score[0]} — ${this.score[1]} // ${this.mode==="cpu"?"CPU "+this.level.toUpperCase():"LOCAL 2P"}`,`BEST RALLY ${this.best}${this.mode==="cpu"?`  •  STREAK ${this.streak}`:""}`,[["REMATCH",()=>this.start(this.mode,this.level)],["ARCADE",this.ui.back]]);}else this.resetRound();}
  hit(index){const b=this.ball,p=this.paddles[index],offset=(b.y-p.y)/.13;b.vx=(index===0?1:-1)*Math.min(870,Math.abs(b.vx)*1.055+13);b.vy+=offset*380;b.vy=Math.max(-620,Math.min(620,b.vy));p.flash=.16;b.squash=.13;this.rally++;if(this.rally>this.best){this.best=this.rally;storage.set("pong-best-rally",this.best);this.ui.best(this.best);}const power=Math.abs(b.vx)/430;audio.hit(power);particleBurst(this.particles,b.x,b.y,index?"#ff4d9b":"#c7ff3c",8,.8);if(power>1.55)this.shake=shake(8,.12);}
  update(dt){if(input.consume("p")||input.consume("escape"))this.paused=!this.paused;if(input.consume("r"))this.resetMatch();if(input.consume("m"))this.ui.mute();if(this.paused)return;this.player(dt);this.cpu(dt);if(this.count>0){this.count-=dt;if(this.count<=0)this.serve();return;}if(this.slow>0)this.slow-=dt;const b=this.ball, factor=this.slow>0?.48:1, rect=this.canvas.getBoundingClientRect(), W=Math.min(rect.width,rect.height*16/9),H=W*9/16;b.x+=b.vx*dt/W*factor;b.y+=b.vy*dt/H*factor;if(b.y<.025||b.y>.975){b.y=Math.max(.025,Math.min(.975,b.y));b.vy*=-1;audio.hit(.5);}if((b.x<.065&&b.vx<0&&Math.abs(b.y-this.paddles[0].y)<.145)||(b.x>.935&&b.vx>0&&Math.abs(b.y-this.paddles[1].y)<.145))this.hit(b.x<.5?0:1);if(b.x<-.04)this.scorePoint(1);if(b.x>1.04)this.scorePoint(0);this.paddles.forEach(p=>p.flash=Math.max(0,p.flash-dt));if(this.rally&&((this.score[0]===6&&this.score[1]>=5)||(this.score[1]===6&&this.score[0]>=5))&&!reducedMotion)this.slow=Math.max(this.slow,.08);}
  draw(){const c=this.ctx,g=this.world(),{w,h}=g;c.clearRect(0,0,w,h);c.fillStyle="#04060b";c.fillRect(0,0,w,h);const sh=updateShake(this.shake,.016);c.save();c.translate(sh.x,sh.y);c.fillStyle="#101b2b";c.fillRect(g.x,g.y,g.W,g.H);c.strokeStyle="#32445a";c.lineWidth=3;c.strokeRect(g.x,g.y,g.W,g.H);c.setLineDash([8,11]);c.beginPath();c.moveTo(g.x+g.W/2,g.y);c.lineTo(g.x+g.W/2,g.y+g.H);c.stroke();c.setLineDash([]);const padW=g.W*.017,padH=g.H*.23;this.paddles.forEach((p,i)=>{c.fillStyle=p.flash?"#fff":"#"+(i?"ff4d9b":"c7ff3c");c.shadowBlur=p.flash?22:8;c.shadowColor=c.fillStyle;rounded(c,g.x+(i?.955:.028)*g.W,g.y+(p.y-.115)*g.H,padW,padH,5);c.shadowBlur=0;});const b=this.ball,bx=g.x+b.x*g.W,by=g.y+b.y*g.H,stretch=Math.min(.65,Math.abs(b.vx)/900),rx=b.r*(1+stretch),ry=b.r*(1-stretch*.5);c.fillStyle="#f7fbff";c.shadowBlur=20;c.shadowColor="#5ae8ff";c.beginPath();c.ellipse(bx,by,rx,ry,0,0,7);c.fill();c.shadowBlur=0;updateParticles(this.particles,.016,(p,a)=>{c.globalAlpha=a;c.fillStyle=p.color;c.fillRect(g.x+p.x*g.W-3,g.y+p.y*g.H-3,6,6);});c.globalAlpha=1;c.restore();c.font=`900 ${Math.max(28,g.H*.1)}px Impact`;c.textAlign="center";c.fillStyle="#eaf2ff";c.fillText(`${this.score[0]}   ${this.score[1]}`,w/2,g.y+g.H*.13);c.font=`12px ui-monospace`;c.fillStyle="#aebac9";c.fillText(this.count>0?Math.ceil(this.count):`RALLY ${this.rally}  //  BEST ${this.best}`,w/2,g.y+g.H*.19);c.textAlign="left";}
  frame(t){if(!this.running)return;const dt=Math.min(.04,(t-this.last)/1000);this.last=t;this.update(dt);this.draw();requestAnimationFrame(x=>this.frame(x));}
  stop(){this.running=false;}
}
