import { input } from "./input.js";
import { audio } from "./audio.js";
import { storage } from "./storage.js";
import { shake, updateShake, particleBurst, updateParticles, fitCanvas, reducedMotion } from "./fx.js";

const N=24, dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}, opposite={up:"down",down:"up",left:"right",right:"left"};
export class Snake {
  constructor(canvas, ui) { this.canvas=canvas;this.ctx=canvas.getContext("2d");this.ui=ui;this.best=storage.get("snake-best",0);this.running=false;this.last=0;this.swipe="";input.bindSwipe(canvas,d=>this.swipe=d); }
  start() { this.reset(); this.running=true; this.last=performance.now(); requestAnimationFrame(t=>this.frame(t)); }
  reset() { this.snake=[{x:7,y:12},{x:6,y:12},{x:5,y:12}];this.dir="right";this.next="right";this.food=this.newFood("normal");this.score=0;this.eaten=0;this.grow=0;this.acc=0;this.step=.135;this.combo=0;this.comboTime=0;this.slow=0;this.dead=0;this.paused=false;this.particles=[];this.trail=[];this.shake=shake(0);this.ui.hide(); }
  newFood(type) { let p; do p={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)}; while(this.snake?.some(s=>s.x===p.x&&s.y===p.y)); return {...p,type}; }
  change(d) { if(d && d!==opposite[this.dir]) this.next=d; }
  die() { if(this.dead) return;this.dead=.42;audio.fail();this.shake=shake(13,.32); if(this.score>this.best){this.best=this.score;storage.set("snake-best",this.best);this.ui.best(this.best);} }
  stepOnce() { this.dir=this.next;const [dx,dy]=dirs[this.dir], h=this.snake[0],n={x:h.x+dx,y:h.y+dy};if(n.x<0||n.y<0||n.x>=N||n.y>=N||this.snake.some(s=>s.x===n.x&&s.y===n.y)){this.die();return;}this.trail.unshift({...h,life:.45});this.snake.unshift(n);if(n.x===this.food.x&&n.y===this.food.y){const f=this.food,g=f.type==="golden";this.eaten++;this.grow+=g?2:1;this.score+=(g?5:1)*(this.combo+1);this.combo=this.comboTime>0?Math.min(9,this.combo+1):0;this.comboTime=1.2;this.slow+=f.type==="slow"?2:0;audio.eat(g);particleBurst(this.particles,(n.x+.5),(n.y+.5),f.type==="golden"?"#ffd550":f.type==="slow"?"#5ae8ff":"#c7ff3c",16,.9);let r=Math.random();this.food=this.newFood(r<.08?"golden":r<.16?"slow":"normal");if(this.eaten%5===0)this.step=Math.max(.058,this.step-.01);}else if(this.grow>0)this.grow--;else this.snake.pop(); }
  update(dt) { if(input.consume("p")||input.consume("escape"))this.paused=!this.paused;if(input.consume("r"))this.reset();if(input.consume("m"))this.ui.mute();["up","down","left","right"].forEach(d=>{if(input.down(d,d==="up"?"w":d==="down"?"s":d==="left"?"a":"d"))this.change(d)});if(this.swipe){this.change(this.swipe);this.swipe="";}if(this.paused||this.dead)return;this.comboTime-=dt;if(this.comboTime<0)this.combo=0;this.slow=Math.max(0,this.slow-dt);this.acc+=dt*(this.slow? .6:1);while(this.acc>this.step){this.acc-=this.step;this.stepOnce();}this.trail.forEach(p=>p.life-=dt);this.trail=this.trail.filter(p=>p.life>0); }
  draw() { const {w,h}=fitCanvas(this.canvas),c=this.ctx,size=Math.min(w,h)*.78,ox=(w-size)/2,oy=(h-size)/2,cell=size/N; c.clearRect(0,0,w,h);c.save();let s=updateShake(this.shake,0);c.translate(s.x,s.y);c.fillStyle="#0d1420";c.fillRect(ox,oy,size,size);c.strokeStyle="#1e2a38";c.lineWidth=1;for(let i=0;i<=N;i++){c.beginPath();c.moveTo(ox+i*cell,oy);c.lineTo(ox+i*cell,oy+size);c.moveTo(ox,oy+i*cell);c.lineTo(ox+size,oy+i*cell);c.stroke();}this.trail.forEach(p=>{c.globalAlpha=p.life/.45*.22;c.fillStyle="#c7ff3c";c.fillRect(ox+p.x*cell,oy+p.y*cell,cell,cell);});c.globalAlpha=1;const f=this.food,cx=ox+(f.x+.5)*cell,cy=oy+(f.y+.5)*cell;c.fillStyle=f.type==="golden"?"#ffd550":f.type==="slow"?"#5ae8ff":"#ff4d9b";c.beginPath();c.arc(cx,cy,cell*(f.type==="golden"?.3:.23),0,7);c.fill();if(f.type!=="normal"){c.strokeStyle=c.fillStyle;c.globalAlpha=.35;c.beginPath();c.arc(cx,cy,cell*.39,0,7);c.stroke();c.globalAlpha=1;}this.snake.slice().reverse().forEach((p,i)=>{c.fillStyle=i===this.snake.length-1?"#e0ff91":"#a6e52d";c.fillRect(ox+p.x*cell+2,oy+p.y*cell+2,cell-4,cell-4);});const head=this.snake[0];c.fillStyle="#10160d";c.fillRect(ox+(head.x+.68)*cell,oy+(head.y+.27)*cell,3,3);c.fillRect(ox+(head.x+.68)*cell,oy+(head.y+.68)*cell,3,3);updateParticles(this.particles,.016,(p,a)=>{c.globalAlpha=a;c.fillStyle=p.color;c.fillRect(ox+p.x*cell-2,oy+p.y*cell-2,4,4);});c.globalAlpha=1;c.restore();c.fillStyle="#eaf2ff";c.font=`${Math.max(13,size*.028)}px ui-monospace`;c.fillText(`SCORE ${this.score}`,ox,oy-18);c.textAlign="right";c.fillStyle="#9ba8b8";c.fillText(`BEST ${this.best}`,ox+size,oy-18);c.textAlign="left";if(this.combo>0){c.fillStyle="#ff4d9b";c.fillText(`x${this.combo+1} COMBO`,ox,oy+size+27);}if(this.slow>0){c.fillStyle="#5ae8ff";c.fillText("SLOW-MO",ox+size-90,oy+size+27);} }
  frame(t){if(!this.running)return;let dt=Math.min(.05,(t-this.last)/1000);this.last=t;if(this.dead){this.dead-=dt;if(this.dead<=0){this.running=false;this.ui.show("SYSTEM CRASH","Snake found a wall.",`SCORE ${this.score}  •  BEST ${this.best}`,[["RETRY",()=>{this.reset();this.running=true;this.last=performance.now();requestAnimationFrame(x=>this.frame(x));}],["ARCADE",this.ui.back]]);}}else this.update(dt);this.draw();requestAnimationFrame(x=>this.frame(x));}
  stop(){this.running=false;}
}
